### Add user to game-announcers
POST http://localhost:4004/odata/v4/game-announcer/UserSet
Content-Type: application/json

{
    "ID": "@123456789",
    "tag": "wonggong#1234",
    "username": "wonggong"
}

### Remove user from game-announcers
POST http://localhost:4004/odata/v4/game-announcer/unsubscribe
Content-Type: application/json

{
    "ID": "@123456789"
}

### forceCreateGuild
POST http://localhost:4004/odata/v4/game-announcer/forceCreateGuild
Content-Type: application/json

{
    "guild": {
        "ID": "123456789"
    }
}